name: git_secret

on:
  workflow_dispatch:

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:

    steps:
      - name: Tell me my secret!
        run: echo "My git secret is ${{secrets.FIRST_SECRET}}"
