name: git_secret

on:
  workflow_dispatch:

jobs:
  top-secret:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
    env:

    steps:
      - name: Tell me my secret!
        run: echo "My git secret is ${{secrets.FIRST_SECRET}}"
         # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
